services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest-fat
    container_name: Stirling-PDF
    deploy:
      resources:
        limits:
          memory: 4G
    depends_on:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP'" ]
      interval: 5s
      timeout: 10s
      retries: 16
    ports:
      - 8080:8080
    # 2. Corrected and consolidated volumes
    volumes:
      - ./StirlingPDF/trainingData:/usr/share/tessdata:rw
      - ./StirlingPDF/extraConfigs:/configs:rw
      - ./StirlingPDF/customFiles:/customFiles:rw
      - ./StirlingPDF/logs:/logs:rw
      - ./StirlingPDF/pipeline:/pipeline:rw
    environment:
      # 3. Enabled login to use the database
      SECURITY_ENABLELOGIN: "true"
      SYSTEM_DATASOURCE_ENABLECUSTOMDATABASE: "true"
      SYSTEM_DATASOURCE_CUSTOMDATABASEURL: "jdbc:postgresql://db:5432/stirling_pdf"
      SYSTEM_DATASOURCE_USERNAME: "admin"
      SYSTEM_DATASOURCE_PASSWORD: "stirling"
      # Other settings from user's file
      DISABLE_ADDITIONAL_FEATURES: "false"
      PUID: 1002
      PGID: 1002
      UMASK: "022"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: Stirling-PDF
      UI_HOMEDESCRIPTION: Demo site for Stirling-PDF Latest-fat with Security and PostgreSQL
      UI_APPNAMENAVBAR: Stirling-PDF Latest-fat-PostgreSQL
      SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "true"
      SHOW_SURVEY: "true"
    restart: on-failure:5

  db:
    image: 'postgres:17.2-alpine'
    restart: on-failure:5
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "stirling_pdf"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "stirling"
    shm_size: "512mb"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin stirling_pdf" ]
      interval: 1s
      timeout: 5s
      retries: 10
    # 2. Corrected and consolidated volume for postgres data
    volumes:
      - ./StirlingPDF/pgdata:/var/lib/postgresql/data

# services:
#   stirling-pdf:
#     image: stirlingtools/stirling-pdf:latest-fat
#     container_name: Stirling-PDF
#     ports:
#       - '8080:8080'
#     volumes:
#       - ./StirlingPDF/trainingData:/usr/share/tessdata
#       - ./StirlingPDF/extraConfigs:/configs
#       - ./StirlingPDF/customFiles:/customFiles/
#       - ./StirlingPDF/logs:/logs/
#       - ./StirlingPDF/pipeline:/pipeline/
#     environment:
#       - LANGS=en_GB,por,spa
