security:
  enableLogin: true # mude para 'true' para habilitar o login
  csrfDisabled: false # mude para 'true' para desabilitar a proteção CSRF (não recomendado para produção)
  loginAttemptCount: 5 # bloqueia a conta do usuário após 5 tentativas; use -1 para desativar
  loginResetTimeMinutes: 120 # tempo de bloqueio da conta em minutos
  loginMethod: all # aceita 'all', 'normal' (apenas usuário/senha), 'oauth2' ou 'saml2'
  initialLogin:
    username: 'andrebadini' # nome de usuário inicial para o primeiro login
    password: '123456' # senha inicial para o primeiro login
  oauth2:
    enabled: false # 'true' para habilitar (enableLogin também deve ser 'true')
    client:
      keycloak:
        issuer: '' # URL do endpoint OpenID Connect Discovery do realm Keycloak
        clientId: ''
        clientSecret: ''
        scopes: openid, profile, email
        useAsUsername: preferred_username # campo a ser usado como nome de usuário [email | name | given_name | family_name | preferred_name]
      google:
        clientId: ''
        clientSecret: ''
        scopes: email, profile
        useAsUsername: email # [email | name | given_name | family_name]
      github:
        clientId: ''
        clientSecret: ''
        scopes: read:user
        useAsUsername: login # [email | login | name]
    issuer: '' # provedor que suporta OpenID Connect Discovery
    clientId: ''
    clientSecret: ''
    autoCreateUser: true # permite a criação automática de usuários não existentes
    blockRegistration: false # nega login SSO sem registro prévio por um admin
    useAsUsername: email # padrão é 'email'; campos customizados podem ser usados
    scopes: openid, profile, email
    provider: google # nome do seu provedor OAuth, ex: 'google' ou 'keycloak'
  saml2:
    enabled: false # apenas para clientes enterprise pagos
    provider: ''
    autoCreateUser: true
    blockRegistration: false
    registrationId: stirling
    idpMetadataUri: https://dev-XXXXXXXX.okta.com/app/externalKey/sso/saml/metadata
    idpSingleLoginUrl: https://dev-XXXXXXXX.okta.com/app/dev-XXXXXXXX_stirlingpdf_1/externalKey/sso/saml
    idpSingleLogoutUrl: https://dev-XXXXXXXX.okta.com/app/dev-XXXXXXXX_stirlingpdf_1/externalKey/slo/saml
    idpIssuer: ''
    idpCert: classpath:okta.cert
    privateKey: classpath:saml-private-key.key
    spCert: classpath:saml-public-cert.crt


legal:
  termsAndConditions: https://www.stirlingpdf.com/terms-and-conditions # URL to the terms and conditions of your application (e.g. https://example.com/terms). Empty string to disable or filename to load from local file in static folder
  privacyPolicy: https://www.stirlingpdf.com/privacy-policy # URL to the privacy policy of your application (e.g. https://example.com/privacy). Empty string to disable or filename to load from local file in static folder
  accessibilityStatement: '' # URL to the accessibility statement of your application (e.g. https://example.com/accessibility). Empty string to disable or filename to load from local file in static folder
  cookiePolicy: '' # URL to the cookie policy of your application (e.g. https://example.com/cookie). Empty string to disable or filename to load from local file in static folder
  impressum: '' # URL to the impressum of your application (e.g. https://example.com/impressum). Empty string to disable or filename to load from local file in static folder

system:
  defaultLocale: en-US # set the default language (e.g. 'de-DE', 'fr-FR', etc)
  googlevisibility: false # 'true' to allow Google visibility (via robots.txt), 'false' to disallow
  enableAlphaFunctionality: false # set to enable functionality which might need more testing before it fully goes live (this feature might make no changes)
  showUpdate: false # see when a new update is available
  showUpdateOnlyAdmin: false # only admins can see when a new update is available, depending on showUpdate it must be set to 'true'
  customHTMLFiles: false # enable to have files placed in /customFiles/templates override the existing template HTML files
  tessdataDir: /usr/share/tessdata # path to the directory containing the Tessdata files. This setting is relevant for Windows systems. For Windows users, this path should be adjusted to point to the appropriate directory where the Tessdata files are stored.
  enableAnalytics: null # set to 'true' to enable analytics, set to 'false' to disable analytics; for enterprise users, this is set to true
  enableUrlToPDF: false # Set to 'true' to enable URL to PDF, INTERNAL ONLY, known security issues, should not be used externally
  disableSanitize: false # set to true to disable Sanitize HTML; (can lead to injections in HTML)
  datasource:
    enableCustomDatabase: false # Enterprise users ONLY, set this property to 'true' if you would like to use your own custom database configuration
    customDatabaseUrl: '' # eg jdbc:postgresql://localhost:5432/postgres, set the url for your own custom database connection. If provided, the type, hostName, port and name are not necessary and will not be used
    username: postgres # set the database username
    password: postgres # set the database password
    type: postgresql # the type of the database to set (e.g. 'h2', 'postgresql')
    hostName: localhost # the host name to use for the database url. Set to 'localhost' when running the app locally. Set to match the name of the container name of your database container when running the app on a server (Docker configuration)
    port: 5432 # set the port number of the database. Ensure this matches the port the database is listening to
    name: postgres # set the name of your database. Should match the name of the database you create
  customPaths:
    pipeline:
      watchedFoldersDir: '' #Defaults to /pipeline/watchedFolders
      finishedFoldersDir: '' #Defaults to /pipeline/finishedFolders
    operations:
      weasyprint: '' #Defaults to /opt/venv/bin/weasyprint
      unoconvert: '' #Defaults to /opt/venv/bin/unoconvert
  fileUploadLimit: '' # Defaults to "". No limit when string is empty. Set a number, between 0 and 999, followed by one of the following strings to set a limit. "KB", "MB", "GB".

ui:
  appName: '' # application's visible name
  homeDescription: '' # short description or tagline shown on the homepage
  appNameNavbar: '' # name displayed on the navigation bar
  languages: [] # If empty, all languages are enabled. To display only German and Polish ["de_DE", "pl_PL"]. British English is always enabled.

endpoints:
  toRemove: [] # list endpoints to disable (e.g. ['img-to-pdf', 'remove-pages'])
  groupsToRemove: [] # list groups to disable (e.g. ['LibreOffice'])

metrics:
  enabled: true # 'true' to enable Info APIs (`/api/*`) endpoints, 'false' to disable

processExecutor:
  sessionLimit: # Process executor instances limits
    libreOfficeSessionLimit: 1
    pdfToHtmlSessionLimit: 1
    qpdfSessionLimit: 4
    tesseractSessionLimit: 1
    pythonOpenCvSessionLimit: 8
    weasyPrintSessionLimit: 16
    installAppSessionLimit: 1
    calibreSessionLimit: 1
  timeoutMinutes: # Process executor timeout in minutes
    libreOfficetimeoutMinutes: 30
    pdfToHtmltimeoutMinutes: 20
    pythonOpenCvtimeoutMinutes: 30
    weasyPrinttimeoutMinutes: 30
    installApptimeoutMinutes: 60
    calibretimeoutMinutes: 30
    tesseractTimeoutMinutes: 30